export const ENTITY_IDENTIFIERS = {
  OWNER: 1,
  WORKER: 2,
  CLIENT: 3,
  GYM: 1,
  EVENT_TYPE_ONE: 1,
  EVENT_TYPE_TWO: 2,
  EVENT_TPL_ONE: 1,
  EVENT_TPL_TWO: 2,
  EVENT_TPL_THREE: 3,
  EVENT_TPL_FOUR: 4,
  VIRTUAL_GYM: 1,
  GYM_ZONE_ONE: 1,
  GYM_ZONE_TWO: 2,
  GYM_ZONE_THREE: 3,
  CALENDAR_ONE: 1,
  CALENDAR_TWO: 2,
  CALENDAR_THREE: 3
};
