import { nanoid } from "nanoid";

export const ENTITY_IDENTIFIERS = {
  OWNER: 1,
  OWNER_EMAIL: 'test@owner.com',
  WORKER: 2,
  WORKER_EMAIL: 'test@worker.com',
  CLIENT: 3,
  CLIENT_EMAIL: 'test@client.com',
  CLIENT_TWO: 4,
  CLIENT_EMAIL_TWO: 'test.two@client.com',
  CLIENT_THREE: 5,
  CLIENT_EMAIL_THREE: 'test.three@client.com',
  TRAINER: 6,
  TRAINER_EMAIL: 'test@trainer.com',
  GYM: 1,
  GYM_CODE: nanoid(8),
  EVENT_TYPE_ONE: 1,
  EVENT_TYPE_TWO: 2,
  EVENT_TPL_ONE: 1,
  EVENT_TPL_TWO: 2,
  EVENT_TPL_THREE: 3,
  EVENT_TPL_FOUR: 4,
  EVENT_ONE: 1,
  EVENT_TWO: 2,
  EVENT_THREE: 3,
  EVENT_FOUR: 4,
  EVENT_FIVE: 5,
  VIRTUAL_GYM: 1,
  GYM_ZONE_ONE: 1,
  GYM_ZONE_TWO: 2,
  GYM_ZONE_THREE: 3,
  CALENDAR_ONE: 1,
  CALENDAR_TWO: 2,
  CALENDAR_THREE: 3
};
